[DEFAULT]
s_network = RPiHotspot
s_psswd = 1234567890

s_mqtt_broker_addr = 192.168.50.10
i_mqtt_port = 1883

; serial debug messages are turned on
i_debug = 1

; wait ten seconds for network connection
i_wifi_timeout = 10000
i_max_count = 120

; sensor reading frequency
i_ota_freq = 60
i_vwc_freq= 5
i_ht_freq = 5
i_tlm_freq = 5
i_dendro_freq = 5

[DEBUG]
s_network = RPiHotspot
s_psswd = 1234567890

s_mqtt_broker_addr = 192.168.50.10
i_mqtt_port = 1883

; serial debug messages are turned on
i_debug = 1

; wait ten seconds for network connection
i_wifi_timeout = 5000
i_max_count = 120

; sensor reading frequency
i_ota_freq = 60
i_vwc_freq= 1
i_ht_freq = 1
i_tlm_freq = 1
i_dendro_freq = 1

; Analog sensor port assignments
; Unassigned: 0
; Teros 10 VWC sensor: 1
; MIJ-02-LS Dendrometer: 2
i_analog_port_0 = 0
i_analog_port_1 = 0
i_analog_port_2 = 0
i_analog_port_3 = 2

[RELEASE]
s_network = RPiHotspot
s_psswd = 1234567890

s_mqtt_broker_addr = 192.168.50.10
i_mqtt_port = 1883

; serial debug messages are turned on
i_debug = 0

; wait ten seconds for network connection
i_wifi_timeout = 10000
i_max_count = 120

; sensor reading frequency
i_ota_freq = 60
i_vwc_freq= 5
i_ht_freq = 5
i_tlm_freq = 5
i_dendro_freq = 5

; Analog sensor port assignments
; Unassigned: 0
; Teros 10 VWC sensor: 1
; MIJ-02-LS Dendrometer: 2
i_analog_port_0 = 0
i_analog_port_1 = 0
i_analog_port_2 = 0
i_analog_port_3 = 2